#auto: true

# markdown的解析器
markdown: kramdown

# 代码高亮
highlighter: rouge
# 分页设置
#paginate: 8
# 链接样式
permalink: /:title/


# title: DXXXX.github.com
title: DXXXX 个人博客

# page中head部分的meta元素
keywords: 激情,使命
description: DXXXX's Blog , DXXX 的个人博客
shotname: DXXXX

# url: http://dxxxx.github.com
url: http://dxxxx.github.io
beian: 京ICP备19013747号-1

# feed: /atom.xml
# atom_path : /atom.xml

author_info: <a href="http://dxxxx.github.io/">DXXXX</a>

